name: cvt
channels:
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
# Python
- python==3.7.6
# Environment support packages
- ipykernel==5.3.0
# Masterclass packages
- jwst_coronagraph_visibility==0.4.4
- matplotlib==3.2.1
