name: jwst-masterclass
channels:
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
# Python
- python==3.7.7
# From conda_python_stable-deps.txt
- _libgcc_mutex==0.1
- ca-certificates==2020.1.1-0
- ld_impl_linux-64==2.33.1
- libstdcxx-ng==9.1.0
- libgcc-ng==9.1.0
- libffi==3.3
- ncurses==6.2
- openssl==1.1.1g
- xz==5.2.5
- zlib==1.2.11
- libedit==3.1.20181209
- readline==8.0
- tk==8.6.8
- sqlite==3.31.1
- certifi==2020.4.5.1
- setuptools==46.4.0
- wheel==0.34.2
- pip==20.0.2
# Environment support packages
- ipykernel==5.1.4
# Masterclass packages
- astroscrappy==1.0.5
- cfitsio==3.440
- cubeviz==0.3.0
- ds9==7.4
- dust_extinction==0.7
- fftw==3.3.4
- fitsblender==0.3.6
- fitsverify==4.18
- ginga==3.0.1
- glue-core==0.15.6
- glue-vispy-viewers==0.12.2
- gwcs==0.11.0
- jplephem==2.9
- jwst-visit-parser==0.1.2
- jwst_footprints==2.2.0
- jwst_gtvt==0.1.0
- jwxml==0.3.0
- matplotlib==3.1.1
- numpy==1.14.6
- pandas==0.25.2
- pandokia==2.4.1
- photutils==0.7.1
- poppy==0.8.0
- pyds9==1.9.0.dev145+gc1bf67a
- pyfftw==0.9.2
- pysiaf==0.5.0
- pysynphot==0.9.14
- python-daemon==2.2.3
- scikit-image==0.15.0
- scikit-learn==0.21.3
- scipy==1.3.1
- stsci==3.2.0
- stsci.tools==3.6.0
- stsci_rtd_theme==0.0.1
- synphot==0.1.3
- webbpsf==0.8.0
- pip:
# Environment support packages
  - apipkg==1.5
  - asdf==2.5.2
  - astropy==4.0.1.post1
  - attrs==19.3.0
  - certifi==2020.4.5.1
  - chardet==3.0.4
  - ci-watson==0.5
  - codecov==2.0.22
  - coverage==5.1
  - crds==7.4.1.3
  - Cython==0.29.16
  - drizzle==1.13.1
  - execnet==1.7.1
  - filelock==3.0.12
  - gwcs==0.13.0
  - idna==2.9
  - importlib-metadata==1.6.0
  - jplephem==2.9
  - jsonschema==3.2.0
  - jwst @ git+https://github.com/spacetelescope/jwst.git@0.16.1
  - lxml==4.5.0
  - more-itertools==8.2.0
  - numpy==1.18.2
  - packaging==20.3
  - Parsley==1.3
  - photutils==0.7.2
  - pluggy==0.13.1
  - psutil==5.7.0
  - py==1.8.1
  - pymssql==2.1.4
  - pyparsing==2.4.7
  - pyrsistent==0.16.0
  - pytest==5.3.5
  - pytest-cov==2.8.1
  - pytest-doctestplus==0.5.0
  - pytest-forked==1.1.3
  - pytest-openfiles==0.5.0
  - pytest-xdist==1.32.0
  - PyYAML==5.3.1
  - requests==2.23.0
  - requests-mock==1.7.0
  - scipy==1.4.1
  - semantic-version==2.8.4
  - six==1.14.0
  - spherical-geometry==1.2.18
  - stsci.image==2.3.3
  - stsci.imagestats==1.6.2
  - stsci.stimage==0.2.4
  - tweakwcs==0.6.4
  - urllib3==1.25.9
  - wcwidth==0.1.9
  - zipp==3.1.0
# Masterclass packages
  - git+https://github.com/astropy/astroquery.git@1527760
  - git+https://github.com/spacetelescope/jwst.git@0.16.1
  - git+https://github.com/spacetelescope/crds.git@7.4.1.3#egg=crds[aws]
  - jwst-backgrounds==1.1.2
  - pandeia-engine==1.5.1
  - git+https://github.com/spacetelescope/pandeia-coronagraphy.git@1d5ad4c
  - git+https://github.com/vortex-exoplanet/VIP.git@104bda7



