name: mirage
channels:
- http://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
    # Python
    - python==3.7.5
    # Environment support packages
    - ipykernel==5.3.0
    # Mirage dependencies
    - asdf==2.6.0
    - astropy==4.0.1.post1
    - gwcs==0.13.0
    - healpy==1.12.5
    - h5py==2.10.0
    - jwxml==0.3.0
    - matplotlib==3.2.1
    - numpy>=1.18.1
    - photutils>=0.7.2
    - pysynphot==0.9.14
    - pytest==5.2.2
    - scipy==1.4.1
    - sphinx==3.0.4
    - yaml==0.1.7
    - pip:
        # Environment support packages
        - git+https://github.com/spacetelescope/crds.git@7.4.1.3#egg=crds[aws]
        # Mirage dependencies
        - jwst-backgrounds==1.1.2
        - git+https://github.com/astropy/astroquery.git@1527760
        - git+https://github.com/spacetelescope/jwst@0.16.1
        - git+https://github.com/spacetelescope/poppy.git@2010aaa
        - git+https://github.com/spacetelescope/webbpsf.git@3575c04
        - git+https://github.com/npirzkal/NIRCAM_Gsim.git@b420a0a
        - git+https://github.com/npirzkal/GRISMCONF.git@c5509a2
        - git+https://github.com/spacetelescope/mirage.git@25df1e3
        - pysiaf==0.9.0
