name: mirage
channels:
- http://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
- asdf>=2.1.0.dev1+ga161518
- astropy==3.2.1
- astroquery>=0.3.8
- gwcs>=0.10a.dev21+g75e92da
- healpy>=1.10
- h5py>=2.8.0
- jwxml>=0.3.0
- matplotlib>=3.0.0
- numpy>=1.16
- photutils>=0.6
- pip>=18.0
- pysynphot>=0.9.12
- pytest>=3.8.1
- python>=3.6,<3.7
- scipy>=1.1.0
- sphinx>=2.1
- yaml>=0.1.7
- ipykernel
- pip:
    - jwst-backgrounds>=1.1.1
    - pysiaf==0.3.0
    - git+https://github.com/spacetelescope/jwst
    - git+https://github.com/spacetelescope/poppy
    - git+https://github.com/spacetelescope/webbpsf
    - git+https://github.com/npirzkal/NIRCAM_Gsim
    - git+https://github.com/npirzkal/GRISMCONF
    - git+https://github.com/spacetelescope/mirage
    - git+https://github.com/spacetelescope/crds.git@7.4.1.2#egg=crds[aws]

