#! /bin/bash

echo ============================= Ubuntu Packages  =======================
apt list --installed

for env in `conda env list  | grep -v "#" | grep -v "^$" | cut -d' ' -f1`; do
    echo ========================= Conda Environment $env =======================
    conda env export -n $env
done
